### HybridAlgorithm

- komentarz autora - SVD działa dobrze, SVD++ jeszcze lepiej :)
- factorization matrix i grupa algorytmow pochodnych do SVD została udworzona na podstawie dobrych wynikow SVD


In [7]:
# HybridAlgorithm - ~1s
!python ./HybridAlgorithm.py

above output:
```
Loading movie ratings...

Computing movie popularity ranks so we can measure novelty later...
Estimating biases using als...
Computing the cosine similarity matrix...
Done computing similarity matrix.
Evaluating  SVD ...
Evaluating accuracy...
Analysis complete.
Evaluating  SVD++ ...
Evaluating accuracy...
Analysis complete.
Evaluating  Random ...
Evaluating accuracy...
Analysis complete.


Algorithm  RMSE       MAE       
SVD        0.9039     0.6984    
SVD++      0.8943     0.6887    
Random     1.4359     1.1493    

Legend:

RMSE:      Root Mean Squared Error. Lower values mean better accuracy.
MAE:       Mean Absolute Error. Lower values mean better accuracy.

Using recommender  SVD

Building recommendation model...
Computing recommendations...

We recommend:
Gladiator (1992) 4.520884890007874
Philadelphia Story, The (1940) 4.420701711947352
Stand by Me (1986) 4.3959589752178365
Moon (2009) 4.372613693384055
Happiness (1998) 4.369493252705134
American Graffiti (1973) 4.353470600109924
And Your Mother Too (Y tu mamÃ¡ tambiÃ©n) (2001) 4.349192492630499
Wallace & Gromit: A Close Shave (1995) 4.3154412154304085
Band of Brothers (2001) 4.315414828016616
Seven Samurai (Shichinin no samurai) (1954) 4.311102920673881

Using recommender  SVD++

Building recommendation model...
Computing recommendations...

We recommend:
Lock, Stock & Two Smoking Barrels (1998) 4.60422766627621
The Imitation Game (2014) 4.457817607681913
Amadeus (1984) 4.322529285260794
Indiana Jones and the Last Crusade (1989) 4.289355864317423
Happiness (1998) 4.260333724293291
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001) 4.229511982111833
Wings of Desire (Himmel Ã¼ber Berlin, Der) (1987) 4.2247114809512345
Grand Day Out with Wallace and Gromit, A (1989) 4.223352198994353
Charade (1963) 4.208953110263677
Snatch (2000) 4.204477673848874

Using recommender  Random

Building recommendation model...
Computing recommendations...

We recommend:
Usual Suspects, The (1995) 5
Legends of the Fall (1994) 5
Trainspotting (1996) 5
Titanic (1997) 5
Happiness (1998) 5
Big Daddy (1999) 5
Spider-Man 2 (2004) 5
Blade Runner (1982) 5
Stand by Me (1986) 5
Indiana Jones and the Last Crusade (1989) 5

```

In [10]:
# HybridTest - ~30min
!python ./HybridTest.py

2022-11-04 09:32:57.238247: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-04 09:32:57.431207: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-04 09:32:58.010145: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-11-04 09:32:58.010217: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

Output from above:

```
2022-11-04 09:32:57.238247: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-04 09:32:57.431207: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-04 09:32:58.010145: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-11-04 09:32:58.010217: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-11-04 09:32:58.010227: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
WARNING:tensorflow:From /home/dkrolik/GitHub/ml_recommender_systems_sundog/venv/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Loading movie ratings...

Computing movie popularity ranks so we can measure novelty later...
Estimating biases using als...
Computing the cosine similarity matrix...
Done computing similarity matrix.
Evaluating  RBM ...
Evaluating accuracy...
Blocked  opposite of sex, the (1998)
Blocked  sex, lies, and videotape (1989)
Blocked  drugstore cowboy (1989)
Blocked  sex and lucia (lucã­a y el sexo) (2001)
Blocked  everything you always wanted to know about sex * but were afraid to ask (1972)
Blocked  love and other drugs (2010)
Blocked  sex tape (2014)
Blocked  relax... it's just sex (1998)
Blocked  sex and the city (2008)
Blocked  sexy beast (2000)
Blocked  sex drive (2008)
Blocked  midsummer night's sex comedy, a (1982)
Blocked  sexmission (seksmisja) (1984)
Blocked  sex ed (2014)
Blocked  sex and the city 2 (2010)
Blocked  the opposite sex (2014)
Blocked  loss of sexual innocence, the (1999)
2022-11-04 09:33:09.908253: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-04 09:33:10.210707: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-11-04 09:33:10.210760: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-11-04 09:33:10.211640: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-04 09:33:10.218969: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Trained epoch  0
Trained epoch  1
Trained epoch  2
Trained epoch  3
Trained epoch  4
Trained epoch  5
Trained epoch  6
Trained epoch  7
Trained epoch  8
Trained epoch  9
Trained epoch  10
Trained epoch  11
Trained epoch  12
Trained epoch  13
Trained epoch  14
Trained epoch  15
Trained epoch  16
Trained epoch  17
Trained epoch  18
Trained epoch  19
Trained epoch  20
Trained epoch  21
Trained epoch  22
Trained epoch  23
Trained epoch  24
Trained epoch  25
Trained epoch  26
Trained epoch  27
Trained epoch  28
Trained epoch  29
Trained epoch  30
Trained epoch  31
Trained epoch  32
Trained epoch  33
Trained epoch  34
Trained epoch  35
Trained epoch  36
Trained epoch  37
Trained epoch  38
Trained epoch  39
Processing user  0
Processing user  50
Processing user  100
Processing user  150
Processing user  200
Processing user  250
Processing user  300
Processing user  350
Processing user  400
Processing user  450
Processing user  500
Processing user  550
Processing user  600
Processing user  650
Analysis complete.
Evaluating  ContentKNN ...
Evaluating accuracy...
Computing content-based similarity matrix...
0  of  8211
100  of  8211
200  of  8211
300  of  8211
400  of  8211
500  of  8211
600  of  8211
700  of  8211
800  of  8211
900  of  8211
1000  of  8211
1100  of  8211
1200  of  8211
1300  of  8211
1400  of  8211
1500  of  8211
1600  of  8211
1700  of  8211
1800  of  8211
1900  of  8211
2000  of  8211
2100  of  8211
2200  of  8211
2300  of  8211
2400  of  8211
2500  of  8211
2600  of  8211
2700  of  8211
2800  of  8211
2900  of  8211
3000  of  8211
3100  of  8211
3200  of  8211
3300  of  8211
3400  of  8211
3500  of  8211
3600  of  8211
3700  of  8211
3800  of  8211
3900  of  8211
4000  of  8211
4100  of  8211
4200  of  8211
4300  of  8211
4400  of  8211
4500  of  8211
4600  of  8211
4700  of  8211
4800  of  8211
4900  of  8211
5000  of  8211
5100  of  8211
5200  of  8211
5300  of  8211
5400  of  8211
5500  of  8211
5600  of  8211
5700  of  8211
5800  of  8211
5900  of  8211
6000  of  8211
6100  of  8211
6200  of  8211
6300  of  8211
6400  of  8211
6500  of  8211
6600  of  8211
6700  of  8211
6800  of  8211
6900  of  8211
7000  of  8211
7100  of  8211
7200  of  8211
7300  of  8211
7400  of  8211
7500  of  8211
7600  of  8211
7700  of  8211
7800  of  8211
7900  of  8211
8000  of  8211
8100  of  8211
8200  of  8211
...done.
Analysis complete.
Evaluating  Hybrid ...
Evaluating accuracy...
Blocked  opposite of sex, the (1998)
Blocked  sex, lies, and videotape (1989)
Blocked  drugstore cowboy (1989)
Blocked  sex and lucia (lucã­a y el sexo) (2001)
Blocked  everything you always wanted to know about sex * but were afraid to ask (1972)
Blocked  love and other drugs (2010)
Blocked  sex tape (2014)
Blocked  relax... it's just sex (1998)
Blocked  sex and the city (2008)
Blocked  sexy beast (2000)
Blocked  sex drive (2008)
Blocked  midsummer night's sex comedy, a (1982)
Blocked  sexmission (seksmisja) (1984)
Blocked  sex ed (2014)
Blocked  sex and the city 2 (2010)
Blocked  the opposite sex (2014)
Blocked  loss of sexual innocence, the (1999)
Trained epoch  0
Trained epoch  1
Trained epoch  2
Trained epoch  3
Trained epoch  4
Trained epoch  5
Trained epoch  6
Trained epoch  7
Trained epoch  8
Trained epoch  9
Trained epoch  10
Trained epoch  11
Trained epoch  12
Trained epoch  13
Trained epoch  14
Trained epoch  15
Trained epoch  16
Trained epoch  17
Trained epoch  18
Trained epoch  19
Trained epoch  20
Trained epoch  21
Trained epoch  22
Trained epoch  23
Trained epoch  24
Trained epoch  25
Trained epoch  26
Trained epoch  27
Trained epoch  28
Trained epoch  29
Trained epoch  30
Trained epoch  31
Trained epoch  32
Trained epoch  33
Trained epoch  34
Trained epoch  35
Trained epoch  36
Trained epoch  37
Trained epoch  38
Trained epoch  39
Processing user  0
Processing user  50
Processing user  100
Processing user  150
Processing user  200
Processing user  250
Processing user  300
Processing user  350
Processing user  400
Processing user  450
Processing user  500
Processing user  550
Processing user  600
Processing user  650
Computing content-based similarity matrix...
0  of  8211
100  of  8211
200  of  8211
300  of  8211
400  of  8211
500  of  8211
600  of  8211
700  of  8211
800  of  8211
900  of  8211
1000  of  8211
1100  of  8211
1200  of  8211
1300  of  8211
1400  of  8211
1500  of  8211
1600  of  8211
1700  of  8211
1800  of  8211
1900  of  8211
2000  of  8211
2100  of  8211
2200  of  8211
2300  of  8211
2400  of  8211
2500  of  8211
2600  of  8211
2700  of  8211
2800  of  8211
2900  of  8211
3000  of  8211
3100  of  8211
3200  of  8211
3300  of  8211
3400  of  8211
3500  of  8211
3600  of  8211
3700  of  8211
3800  of  8211
3900  of  8211
4000  of  8211
4100  of  8211
4200  of  8211
4300  of  8211
4400  of  8211
4500  of  8211
4600  of  8211
4700  of  8211
4800  of  8211
4900  of  8211
5000  of  8211
5100  of  8211
5200  of  8211
5300  of  8211
5400  of  8211
5500  of  8211
5600  of  8211
5700  of  8211
5800  of  8211
5900  of  8211
6000  of  8211
6100  of  8211
6200  of  8211
6300  of  8211
6400  of  8211
6500  of  8211
6600  of  8211
6700  of  8211
6800  of  8211
6900  of  8211
7000  of  8211
7100  of  8211
7200  of  8211
7300  of  8211
7400  of  8211
7500  of  8211
7600  of  8211
7700  of  8211
7800  of  8211
7900  of  8211
8000  of  8211
8100  of  8211
8200  of  8211
...done.
Analysis complete.


Algorithm  RMSE       MAE       
RBM        1.1891     0.9931    
ContentKNN 0.9375     0.7263    
Hybrid     0.9953     0.8124    

Legend:

RMSE:      Root Mean Squared Error. Lower values mean better accuracy.
MAE:       Mean Absolute Error. Lower values mean better accuracy.

Using recommender  RBM

Building recommendation model...
Blocked  drugstore cowboy (1989)
Blocked  love & sex (2000)
Blocked  sex, lies, and videotape (1989)
Blocked  sexy beast (2000)
Blocked  sex and lucia (lucã­a y el sexo) (2001)
Blocked  sex tape (2014)
Blocked  everything you always wanted to know about sex * but were afraid to ask (1972)
Blocked  opposite of sex, the (1998)
Blocked  love and other drugs (2010)
Blocked  sex: the annabel chong story (1999)
Blocked  sex drive (2008)
Blocked  sexmission (seksmisja) (1984)
Blocked  sex and the city (2008)
Blocked  talking about sex (1994)
Blocked  relax... it's just sex (1998)
Blocked  loss of sexual innocence, the (1999)
Blocked  midsummer night's sex comedy, a (1982)
Blocked  sex and the city 2 (2010)
Blocked  sex ed (2014)
Blocked  the opposite sex (2014)
Trained epoch  0
Trained epoch  1
Trained epoch  2
Trained epoch  3
Trained epoch  4
Trained epoch  5
Trained epoch  6
Trained epoch  7
Trained epoch  8
Trained epoch  9
Trained epoch  10
Trained epoch  11
Trained epoch  12
Trained epoch  13
Trained epoch  14
Trained epoch  15
Trained epoch  16
Trained epoch  17
Trained epoch  18
Trained epoch  19
Trained epoch  20
Trained epoch  21
Trained epoch  22
Trained epoch  23
Trained epoch  24
Trained epoch  25
Trained epoch  26
Trained epoch  27
Trained epoch  28
Trained epoch  29
Trained epoch  30
Trained epoch  31
Trained epoch  32
Trained epoch  33
Trained epoch  34
Trained epoch  35
Trained epoch  36
Trained epoch  37
Trained epoch  38
Trained epoch  39
Processing user  0
Processing user  50
Processing user  100
Processing user  150
Processing user  200
Processing user  250
Processing user  300
Processing user  350
Processing user  400
Processing user  450
Processing user  500
Processing user  550
Processing user  600
Processing user  650
Computing recommendations...

We recommend:
Howl's Moving Castle (Hauru no ugoku shiro) (2004) 3.355652
Hurt Locker, The (2008) 3.3554246
Harry Potter and the Half-Blood Prince (2009) 3.3551476
Downfall (Untergang, Der) (2004) 3.354901
Harry Potter and the Deathly Hallows: Part 2 (2011) 3.353933
On the Waterfront (1954) 3.3464653
Maltese Falcon, The (a.k.a. Dangerous Female) (1931) 3.3455944
NausicaÃ¤ of the Valley of the Wind (Kaze no tani no Naushika) (1984) 3.3437233
You Can Count on Me (2000) 3.3428183
Amores Perros (Love's a Bitch) (2000) 3.3394096

Using recommender  ContentKNN

Building recommendation model...
Computing content-based similarity matrix...
0  of  9066
100  of  9066
200  of  9066
300  of  9066
400  of  9066
500  of  9066
600  of  9066
700  of  9066
800  of  9066
900  of  9066
1000  of  9066
1100  of  9066
1200  of  9066
1300  of  9066
1400  of  9066
1500  of  9066
1600  of  9066
1700  of  9066
1800  of  9066
1900  of  9066
2000  of  9066
2100  of  9066
2200  of  9066
2300  of  9066
2400  of  9066
2500  of  9066
2600  of  9066
2700  of  9066
2800  of  9066
2900  of  9066
3000  of  9066
3100  of  9066
3200  of  9066
3300  of  9066
3400  of  9066
3500  of  9066
3600  of  9066
3700  of  9066
3800  of  9066
3900  of  9066
4000  of  9066
4100  of  9066
4200  of  9066
4300  of  9066
4400  of  9066
4500  of  9066
4600  of  9066
4700  of  9066
4800  of  9066
4900  of  9066
5000  of  9066
5100  of  9066
5200  of  9066
5300  of  9066
5400  of  9066
5500  of  9066
5600  of  9066
5700  of  9066
5800  of  9066
5900  of  9066
6000  of  9066
6100  of  9066
6200  of  9066
6300  of  9066
6400  of  9066
6500  of  9066
6600  of  9066
6700  of  9066
6800  of  9066
6900  of  9066
7000  of  9066
7100  of  9066
7200  of  9066
7300  of  9066
7400  of  9066
7500  of  9066
7600  of  9066
7700  of  9066
7800  of  9066
7900  of  9066
8000  of  9066
8100  of  9066
8200  of  9066
8300  of  9066
8400  of  9066
8500  of  9066
8600  of  9066
8700  of  9066
8800  of  9066
8900  of  9066
9000  of  9066
...done.
Computing recommendations...

We recommend:
Presidio, The (1988) 3.841314676872932
Femme Nikita, La (Nikita) (1990) 3.839613347087336
Wyatt Earp (1994) 3.8125061475551796
Shooter, The (1997) 3.8125061475551796
Bad Girls (1994) 3.8125061475551796
The Hateful Eight (2015) 3.812506147555179
True Grit (2010) 3.812506147555179
Open Range (2003) 3.812506147555179
Big Easy, The (1987) 3.7835412549266985
Point Break (1991) 3.764158410102279

Using recommender  Hybrid

Building recommendation model...
Blocked  drugstore cowboy (1989)
Blocked  love & sex (2000)
Blocked  sex, lies, and videotape (1989)
Blocked  sexy beast (2000)
Blocked  sex and lucia (lucã­a y el sexo) (2001)
Blocked  sex tape (2014)
Blocked  everything you always wanted to know about sex * but were afraid to ask (1972)
Blocked  opposite of sex, the (1998)
Blocked  love and other drugs (2010)
Blocked  sex: the annabel chong story (1999)
Blocked  sex drive (2008)
Blocked  sexmission (seksmisja) (1984)
Blocked  sex and the city (2008)
Blocked  talking about sex (1994)
Blocked  relax... it's just sex (1998)
Blocked  loss of sexual innocence, the (1999)
Blocked  midsummer night's sex comedy, a (1982)
Blocked  sex and the city 2 (2010)
Blocked  sex ed (2014)
Blocked  the opposite sex (2014)
Trained epoch  0
Trained epoch  1
Trained epoch  2
Trained epoch  3
Trained epoch  4
Trained epoch  5
Trained epoch  6
Trained epoch  7
Trained epoch  8
Trained epoch  9
Trained epoch  10
Trained epoch  11
Trained epoch  12
Trained epoch  13
Trained epoch  14
Trained epoch  15
Trained epoch  16
Trained epoch  17
Trained epoch  18
Trained epoch  19
Trained epoch  20
Trained epoch  21
Trained epoch  22
Trained epoch  23
Trained epoch  24
Trained epoch  25
Trained epoch  26
Trained epoch  27
Trained epoch  28
Trained epoch  29
Trained epoch  30
Trained epoch  31
Trained epoch  32
Trained epoch  33
Trained epoch  34
Trained epoch  35
Trained epoch  36
Trained epoch  37
Trained epoch  38
Trained epoch  39
Processing user  0
Processing user  50
Processing user  100
Processing user  150
Processing user  200
Processing user  250
Processing user  300
Processing user  350
Processing user  400
Processing user  450
Processing user  500
Processing user  550
Processing user  600
Processing user  650
Computing content-based similarity matrix...
0  of  9066
100  of  9066
200  of  9066
300  of  9066
400  of  9066
500  of  9066
600  of  9066
700  of  9066
800  of  9066
900  of  9066
1000  of  9066
1100  of  9066
1200  of  9066
1300  of  9066
1400  of  9066
1500  of  9066
1600  of  9066
1700  of  9066
1800  of  9066
1900  of  9066
2000  of  9066
2100  of  9066
2200  of  9066
2300  of  9066
2400  of  9066
2500  of  9066
2600  of  9066
2700  of  9066
2800  of  9066
2900  of  9066
3000  of  9066
3100  of  9066
3200  of  9066
3300  of  9066
3400  of  9066
3500  of  9066
3600  of  9066
3700  of  9066
3800  of  9066
3900  of  9066
4000  of  9066
4100  of  9066
4200  of  9066
4300  of  9066
4400  of  9066
4500  of  9066
4600  of  9066
4700  of  9066
4800  of  9066
4900  of  9066
5000  of  9066
5100  of  9066
5200  of  9066
5300  of  9066
5400  of  9066
5500  of  9066
5600  of  9066
5700  of  9066
5800  of  9066
5900  of  9066
6000  of  9066
6100  of  9066
6200  of  9066
6300  of  9066
6400  of  9066
6500  of  9066
6600  of  9066
6700  of  9066
6800  of  9066
6900  of  9066
7000  of  9066
7100  of  9066
7200  of  9066
7300  of  9066
7400  of  9066
7500  of  9066
7600  of  9066
7700  of  9066
7800  of  9066
7900  of  9066
8000  of  9066
8100  of  9066
8200  of  9066
8300  of  9066
8400  of  9066
8500  of  9066
8600  of  9066
8700  of  9066
8800  of  9066
8900  of  9066
9000  of  9066
...done.
Computing recommendations...

We recommend:
True Grit (2010) 3.5562101345914936
Bowling for Columbine (2002) 3.543608255669773
Fahrenheit 9/11 (2004) 3.543608255669773
White Stripes Under Great White Northern Lights, The (2009) 3.543608255669773
Roger & Me (1989) 3.543608255669773
Step Into Liquid (2002) 3.543608255669773
Inside Job (2010) 3.543608255669773
Crumb (1994) 3.543608255669773
Hoop Dreams (1994) 3.543608255669773
War Room, The (1993) 3.543608255669773

```